name: myfirstworkflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: list all the files
        run: ls   
      - name: create a folder
        run: mkdir -p path/to/artifact
      - name: copy the artifact 
        run: cp -r  *.*  path/to/artifact
      - name: upload artifact  
        uses: actions/upload-artifact@v3
        with:
         name: my-artifact
         path: path/to/artifact/ 
      - name: list the files after upload
        run: ls   
      - name: download artifact
        uses: actions/upload-artifact@v3
        with:
         name: my-artifact
         path: path/to/artifact/ 
      - name: list the files after download
        run: ls

           